import { z } from "zod";
import type { ResourceAnnotationsPayload } from "../resource-annotation.js";
import type { Equal, Expect } from "../types.js";

export const resourceAnnotationsPayloadSchema = z.object({
  env: z.string(),
  site: z.string(),
  slot: z.string(),
  scope: z.string(),
  service: z.string(),
  resource_type: z.string(),
  metadata: z.record(z.string()).optional(),
});

// Test cases for ResourceAnnotationsPayload
type TestResourceAnnotationsPayload = Expect<
  Equal<z.infer<typeof resourceAnnotationsPayloadSchema>, ResourceAnnotationsPayload>
>;

export const baseInfraStateResourceSchema = {
  /**
   * Generated by @ref `ResourceAnnotation.generateId()`
   */
  ism_annotation_id: z.string().optional(),
  /**
   * Annotations for the resource
   */
  ism_annotations_payload: resourceAnnotationsPayloadSchema.optional(),
};
